/// Flutter icons Radio
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Radio
///      fonts:
///       - asset: fonts/Radio.ttf
///
/// 
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class Radio {
  Radio._();

  static const _kFontFam = 'Radio';
  static const _kFontPkg = null;

  static const IconData radio_tower = IconData(0xf393, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
