/// Flutter icons TidalHome
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TidalHome
///      fonts:
///       - asset: fonts/TidalHome.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class TidalHome {
  TidalHome._();

  static const _kFontFam = 'TidalHome';
  static const _kFontPkg = null;

  static const IconData video = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
